# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pAqHB9b-Xl3sEJ3zIDLzEOpXVv0CJYb
"""

# Bước 1: Cài đặt thư viện cần thiết
!pip install ultralytics
!pip install gdown
from google.colab import files as colab_files
import zipfile
import os
from ultralytics import YOLO

# Bước 1: Tải và giải nén dữ liệu
uploaded = colab_files.upload()

# Đường dẫn tới tệp ZIP đã tải lên
zip_path = "/content/dog and cat.v1i.yolov5pytorch.zip"
extract_path = "/content/dataset"

# Giải nén tệp ZIP
os.makedirs(extract_path, exist_ok=True)
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Kiểm tra cấu trúc tệp
print("Danh sách tệp trong thư mục dữ liệu:")
for root, dirs, files in os.walk(extract_path):
    level = root.replace(extract_path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 4 * (level + 1)
    for f in files:
        print(f"{subindent}{f}")

# Bước 2: Xác minh tệp YAML cấu hình
yaml_path = "/content/dataset/data.yaml"
if os.path.exists(yaml_path):
    print(f"Cấu hình dữ liệu: {yaml_path}")
else:
    raise FileNotFoundError(f"Tệp dataset.yaml không tồn tại tại: {yaml_path}")

# Bước 3: Huấn luyện mô hình YOLO
model = YOLO("yolov5s.pt")  # Sử dụng YOLOv5s pre-trained model

# Huấn luyện
model.train(
    data=yaml_path,  # Đường dẫn tệp YAML
    epochs=50,       # Số epoch
    imgsz=640,       # Kích thước ảnh
    batch=16,        # Batch size
    device=0         # Chạy trên GPU (nếu có)
)


# Đường dẫn đến thư mục kết quả huấn luyện
result_dir = "/content/runs/detect/train"

# Kiểm tra thư mục huấn luyện
if not os.path.exists(result_dir):
    print(f"Thư mục {result_dir} không tồn tại. Kiểm tra xem huấn luyện đã hoàn tất chưa.")
else:
    # Đường dẫn đến tệp best.pt
    weights_path ="/content/runs/detect/train/weights/best.pt"

    # Kiểm tra tệp best.pt đã tồn tại hay chưa
    if os.path.exists(weights_path):
        print(f"Tải mô hình: {weights_path}")
        colab_files.download(weights_path)
    else:
        print(f"Tệp {weights_path} không tồn tại.")